name: "Setup Build Environment"
description: "Install Python build dependencies for Nuitka builds"

runs:
  using: "composite"
  steps:

    - name: Create virtual environment
      shell: bash
      run: |
        python3 -m venv .venv
        echo "PATH=$PWD/.venv/bin:$PATH" >> $GITHUB_ENV

    - name: Install build dependencies in venv
      shell: bash
      run: |
        . .venv/bin/activate
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        pip install "nuitka>=2.8"
