name: "Setup Build Environment"
description: "Install Python build dependencies for Nuitka builds"

inputs:
  architecture:
    description: "Architecture to configure (x64 or x86 for Windows)"
    required: false
    default: "x64"

runs:
  using: "composite"
  steps:

    - name: Install pip + setuptools
      shell: bash
      run: |
        python3 -m pip install --upgrade pip wheel setuptools

    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m pip install -r requirements.txt
        python3 -m pip install "nuitka>=2.8"
