name: "Setup Build Environment"
description: "Install Python build dependencies for Nuitka builds"

runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Detect OS and create venv
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
            py -3 -m venv .venv
            echo "PATH=$PWD/.venv/Scripts:$PATH" >> $GITHUB_ENV
        else
            python3 -m venv .venv
            echo "PATH=$PWD/.venv/bin:$PATH" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      shell: bash
      run: |
        source .venv/bin/activate || source .venv/Scripts/activate

        pip install --upgrade wheel setuptools
        pip install -r requirements.txt
        pip install "nuitka>=2.8"
