name: "Setup Build"
description: "Install Python + dependencies"

runs:
  using: "composite"
  steps:

    - name: Detect OS and create venv
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          python -m venv .venv
          echo "VENV_ACTIVATE=.venv/Scripts/activate" >> $GITHUB_ENV
        else
          python -m venv .venv
          echo "VENV_ACTIVATE=source .venv/bin/activate" >> $GITHUB_ENV
        fi

    - name: Install pip + deps
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        python -m pip install --upgrade pip setuptools wheel

    - name: Install project requirements
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        pip install -r requirements.txt

    - name: Install Nuitka
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        pip install "nuitka>=2.8" ordered-set zstandard
