name: "Setup Build"
description: "Install Python + dependencies"

runs:
  using: "composite"
  steps:
    - name: Detect OS and create venv
      shell: bash
      run: |
        python -m venv .venv
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # Use 'source' for bash on Windows
          echo "VENV_ACTIVATE=source .venv/Scripts/activate" >> $GITHUB_ENV
        else
          echo "VENV_ACTIVATE=source .venv/bin/activate" >> $GITHUB_ENV
        fi

    - name: Install pip + deps
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        python -m pip install --upgrade pip setuptools wheel

    - name: Install project requirements
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        pip install -r requirements.txt

    - name: Install Nuitka
      shell: bash
      run: |
        eval "$VENV_ACTIVATE"
        pip install "nuitka==2.8.6" ordered-set zstandard
